name: Pruebas Unitarias Java
on: 
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Ejecutar pruebas
      run: mvn clean test
    
    - name: Generar reporte de cobertura
      run: mvn jacoco:report
    
    - name: Verificar reportes
      run: dir target\surefire-reports\
    
    - name: Publicar resultados de pruebas
      uses: dorny/test-reporter@v1.13.1
      if: success() || failure()
      with:
        name: Maven Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit